import { VizSeedBuilder as IVizSeedBuilder, ChartSpec, NestedMeasure } from '../types';
import { DataSet as IDataSet, FieldInferenceOptions } from '../types/data';
import { ChartType } from '../types/charts';
import { FieldMap, FieldSelection } from '../pipeline/PipelineCore';
export declare class VizSeedBuilder implements IVizSeedBuilder {
    private dataset;
    private fieldSelection;
    private fieldMap;
    private data;
    private chartType;
    private encodes;
    private visualStyle;
    private theme;
    private version;
    private vizSeedDSL;
    constructor(rows: Record<string, any>[], options?: FieldInferenceOptions);
    constructor(dataset: IDataSet);
    private createFieldDefinition;
    private extractFieldDomain;
    private addFieldToMap;
    static from(vizSeedDSL: any): VizSeedBuilder;
    getDataSet(): IDataSet;
    getAvailableFields(): string[];
    getAvailableDimensions(): string[];
    getAvailableMeasures(): string[];
    getSelectedFields(): string[];
    setDimensions(dimensions: string[]): VizSeedBuilder;
    setMeasures(measures: NestedMeasure<string>[]): VizSeedBuilder;
    addDimensionToArray(dimension: string): VizSeedBuilder;
    addMeasureToArray(measure: string): VizSeedBuilder;
    getDimensions(): string[];
    getMeasures(): string[];
    setIndicatorChart(indicatorName: string, vizSeedDSL: any): VizSeedBuilder;
    getIndicatorChartSpecs(): Record<string, any>;
    setRowDimensions(rowDimensions: string[]): VizSeedBuilder;
    setColumnDimensions(columnDimensions: string[]): VizSeedBuilder;
    addRowDimensionToArray(dimension: string): VizSeedBuilder;
    addColumnDimensionToArray(dimension: string): VizSeedBuilder;
    getRowDimensions(): string[];
    getColumnDimensions(): string[];
    getFieldMap(): FieldMap;
    setFieldMap(fieldMap: FieldMap): VizSeedBuilder;
    getFieldSelection(): FieldSelection;
    setFieldSelection(fieldSelection: FieldSelection): VizSeedBuilder;
    setFieldAlias(fieldId: string, alias: string): VizSeedBuilder;
    getAvailableFieldNames(): string[];
    hasField(fieldName: string): boolean;
    private updateDataMap;
    setChartType(type: string): VizSeedBuilder;
    setChartType(type: ChartType): VizSeedBuilder;
    setTitle(title: string): VizSeedBuilder;
    setLegend(visible?: boolean): VizSeedBuilder;
    setLabel(visible?: boolean): VizSeedBuilder;
    setTooltip(visible?: boolean): VizSeedBuilder;
    setStyle(styleOptions: any): VizSeedBuilder;
    build(): any;
    buildSpec(): ChartSpec;
    private validateFieldRequirements;
}
//# sourceMappingURL=VizSeedBuilder.d.ts.map